// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/human.proto

package com.xiaotiangege.serialize.protobuf;

public final class Human {
  private Human() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TeacherOrBuilder extends
      // @@protoc_insertion_point(interface_extends:message.Teacher)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code message.Teacher}
   */
  public  static final class Teacher extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:message.Teacher)
      TeacherOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Teacher.newBuilder() to construct.
    private Teacher(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Teacher() {
      id_ = 0;
      name_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Teacher(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xiaotiangege.serialize.protobuf.Human.internal_static_message_Teacher_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xiaotiangege.serialize.protobuf.Human.internal_static_message_Teacher_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xiaotiangege.serialize.protobuf.Human.Teacher.class, com.xiaotiangege.serialize.protobuf.Human.Teacher.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.xiaotiangege.serialize.protobuf.Human.Teacher)) {
        return super.equals(obj);
      }
      com.xiaotiangege.serialize.protobuf.Human.Teacher other = (com.xiaotiangege.serialize.protobuf.Human.Teacher) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getName()
          .equals(other.getName());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.xiaotiangege.serialize.protobuf.Human.Teacher parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xiaotiangege.serialize.protobuf.Human.Teacher parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xiaotiangege.serialize.protobuf.Human.Teacher parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xiaotiangege.serialize.protobuf.Human.Teacher parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xiaotiangege.serialize.protobuf.Human.Teacher parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xiaotiangege.serialize.protobuf.Human.Teacher parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xiaotiangege.serialize.protobuf.Human.Teacher parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xiaotiangege.serialize.protobuf.Human.Teacher parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xiaotiangege.serialize.protobuf.Human.Teacher parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.xiaotiangege.serialize.protobuf.Human.Teacher parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xiaotiangege.serialize.protobuf.Human.Teacher parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xiaotiangege.serialize.protobuf.Human.Teacher parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.xiaotiangege.serialize.protobuf.Human.Teacher prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code message.Teacher}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:message.Teacher)
        com.xiaotiangege.serialize.protobuf.Human.TeacherOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xiaotiangege.serialize.protobuf.Human.internal_static_message_Teacher_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xiaotiangege.serialize.protobuf.Human.internal_static_message_Teacher_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xiaotiangege.serialize.protobuf.Human.Teacher.class, com.xiaotiangege.serialize.protobuf.Human.Teacher.Builder.class);
      }

      // Construct using com.xiaotiangege.serialize.protobuf.Human.Teacher.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xiaotiangege.serialize.protobuf.Human.internal_static_message_Teacher_descriptor;
      }

      @java.lang.Override
      public com.xiaotiangege.serialize.protobuf.Human.Teacher getDefaultInstanceForType() {
        return com.xiaotiangege.serialize.protobuf.Human.Teacher.getDefaultInstance();
      }

      @java.lang.Override
      public com.xiaotiangege.serialize.protobuf.Human.Teacher build() {
        com.xiaotiangege.serialize.protobuf.Human.Teacher result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.xiaotiangege.serialize.protobuf.Human.Teacher buildPartial() {
        com.xiaotiangege.serialize.protobuf.Human.Teacher result = new com.xiaotiangege.serialize.protobuf.Human.Teacher(this);
        result.id_ = id_;
        result.name_ = name_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xiaotiangege.serialize.protobuf.Human.Teacher) {
          return mergeFrom((com.xiaotiangege.serialize.protobuf.Human.Teacher)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xiaotiangege.serialize.protobuf.Human.Teacher other) {
        if (other == com.xiaotiangege.serialize.protobuf.Human.Teacher.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.xiaotiangege.serialize.protobuf.Human.Teacher parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.xiaotiangege.serialize.protobuf.Human.Teacher) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:message.Teacher)
    }

    // @@protoc_insertion_point(class_scope:message.Teacher)
    private static final com.xiaotiangege.serialize.protobuf.Human.Teacher DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.xiaotiangege.serialize.protobuf.Human.Teacher();
    }

    public static com.xiaotiangege.serialize.protobuf.Human.Teacher getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Teacher>
        PARSER = new com.google.protobuf.AbstractParser<Teacher>() {
      @java.lang.Override
      public Teacher parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Teacher(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Teacher> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Teacher> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.xiaotiangege.serialize.protobuf.Human.Teacher getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface StudentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:message.Student)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code message.Student}
   */
  public  static final class Student extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:message.Student)
      StudentOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Student.newBuilder() to construct.
    private Student(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Student() {
      id_ = 0;
      name_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Student(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xiaotiangege.serialize.protobuf.Human.internal_static_message_Student_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xiaotiangege.serialize.protobuf.Human.internal_static_message_Student_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xiaotiangege.serialize.protobuf.Human.Student.class, com.xiaotiangege.serialize.protobuf.Human.Student.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.xiaotiangege.serialize.protobuf.Human.Student)) {
        return super.equals(obj);
      }
      com.xiaotiangege.serialize.protobuf.Human.Student other = (com.xiaotiangege.serialize.protobuf.Human.Student) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getName()
          .equals(other.getName());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.xiaotiangege.serialize.protobuf.Human.Student parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xiaotiangege.serialize.protobuf.Human.Student parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xiaotiangege.serialize.protobuf.Human.Student parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xiaotiangege.serialize.protobuf.Human.Student parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xiaotiangege.serialize.protobuf.Human.Student parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xiaotiangege.serialize.protobuf.Human.Student parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xiaotiangege.serialize.protobuf.Human.Student parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xiaotiangege.serialize.protobuf.Human.Student parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xiaotiangege.serialize.protobuf.Human.Student parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.xiaotiangege.serialize.protobuf.Human.Student parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xiaotiangege.serialize.protobuf.Human.Student parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xiaotiangege.serialize.protobuf.Human.Student parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.xiaotiangege.serialize.protobuf.Human.Student prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code message.Student}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:message.Student)
        com.xiaotiangege.serialize.protobuf.Human.StudentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xiaotiangege.serialize.protobuf.Human.internal_static_message_Student_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xiaotiangege.serialize.protobuf.Human.internal_static_message_Student_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xiaotiangege.serialize.protobuf.Human.Student.class, com.xiaotiangege.serialize.protobuf.Human.Student.Builder.class);
      }

      // Construct using com.xiaotiangege.serialize.protobuf.Human.Student.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xiaotiangege.serialize.protobuf.Human.internal_static_message_Student_descriptor;
      }

      @java.lang.Override
      public com.xiaotiangege.serialize.protobuf.Human.Student getDefaultInstanceForType() {
        return com.xiaotiangege.serialize.protobuf.Human.Student.getDefaultInstance();
      }

      @java.lang.Override
      public com.xiaotiangege.serialize.protobuf.Human.Student build() {
        com.xiaotiangege.serialize.protobuf.Human.Student result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.xiaotiangege.serialize.protobuf.Human.Student buildPartial() {
        com.xiaotiangege.serialize.protobuf.Human.Student result = new com.xiaotiangege.serialize.protobuf.Human.Student(this);
        result.id_ = id_;
        result.name_ = name_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xiaotiangege.serialize.protobuf.Human.Student) {
          return mergeFrom((com.xiaotiangege.serialize.protobuf.Human.Student)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xiaotiangege.serialize.protobuf.Human.Student other) {
        if (other == com.xiaotiangege.serialize.protobuf.Human.Student.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.xiaotiangege.serialize.protobuf.Human.Student parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.xiaotiangege.serialize.protobuf.Human.Student) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:message.Student)
    }

    // @@protoc_insertion_point(class_scope:message.Student)
    private static final com.xiaotiangege.serialize.protobuf.Human.Student DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.xiaotiangege.serialize.protobuf.Human.Student();
    }

    public static com.xiaotiangege.serialize.protobuf.Human.Student getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Student>
        PARSER = new com.google.protobuf.AbstractParser<Student>() {
      @java.lang.Override
      public Student parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Student(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Student> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Student> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.xiaotiangege.serialize.protobuf.Human.Student getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PeopleOrBuilder extends
      // @@protoc_insertion_point(interface_extends:message.People)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.message.People.DataType type = 1;</code>
     */
    int getTypeValue();
    /**
     * <code>.message.People.DataType type = 1;</code>
     */
    com.xiaotiangege.serialize.protobuf.Human.People.DataType getType();

    /**
     * <code>.message.Student stu = 2;</code>
     */
    boolean hasStu();
    /**
     * <code>.message.Student stu = 2;</code>
     */
    com.xiaotiangege.serialize.protobuf.Human.Student getStu();
    /**
     * <code>.message.Student stu = 2;</code>
     */
    com.xiaotiangege.serialize.protobuf.Human.StudentOrBuilder getStuOrBuilder();

    /**
     * <code>.message.Teacher teacher = 3;</code>
     */
    boolean hasTeacher();
    /**
     * <code>.message.Teacher teacher = 3;</code>
     */
    com.xiaotiangege.serialize.protobuf.Human.Teacher getTeacher();
    /**
     * <code>.message.Teacher teacher = 3;</code>
     */
    com.xiaotiangege.serialize.protobuf.Human.TeacherOrBuilder getTeacherOrBuilder();

    public com.xiaotiangege.serialize.protobuf.Human.People.DataMsgCase getDataMsgCase();
  }
  /**
   * Protobuf type {@code message.People}
   */
  public  static final class People extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:message.People)
      PeopleOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use People.newBuilder() to construct.
    private People(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private People() {
      type_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private People(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 18: {
              com.xiaotiangege.serialize.protobuf.Human.Student.Builder subBuilder = null;
              if (dataMsgCase_ == 2) {
                subBuilder = ((com.xiaotiangege.serialize.protobuf.Human.Student) dataMsg_).toBuilder();
              }
              dataMsg_ =
                  input.readMessage(com.xiaotiangege.serialize.protobuf.Human.Student.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.xiaotiangege.serialize.protobuf.Human.Student) dataMsg_);
                dataMsg_ = subBuilder.buildPartial();
              }
              dataMsgCase_ = 2;
              break;
            }
            case 26: {
              com.xiaotiangege.serialize.protobuf.Human.Teacher.Builder subBuilder = null;
              if (dataMsgCase_ == 3) {
                subBuilder = ((com.xiaotiangege.serialize.protobuf.Human.Teacher) dataMsg_).toBuilder();
              }
              dataMsg_ =
                  input.readMessage(com.xiaotiangege.serialize.protobuf.Human.Teacher.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.xiaotiangege.serialize.protobuf.Human.Teacher) dataMsg_);
                dataMsg_ = subBuilder.buildPartial();
              }
              dataMsgCase_ = 3;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xiaotiangege.serialize.protobuf.Human.internal_static_message_People_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xiaotiangege.serialize.protobuf.Human.internal_static_message_People_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xiaotiangege.serialize.protobuf.Human.People.class, com.xiaotiangege.serialize.protobuf.Human.People.Builder.class);
    }

    /**
     * Protobuf enum {@code message.People.DataType}
     */
    public enum DataType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>TEACHER = 0;</code>
       */
      TEACHER(0),
      /**
       * <code>STUDENT = 1;</code>
       */
      STUDENT(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>TEACHER = 0;</code>
       */
      public static final int TEACHER_VALUE = 0;
      /**
       * <code>STUDENT = 1;</code>
       */
      public static final int STUDENT_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DataType valueOf(int value) {
        return forNumber(value);
      }

      public static DataType forNumber(int value) {
        switch (value) {
          case 0: return TEACHER;
          case 1: return STUDENT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<DataType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          DataType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<DataType>() {
              public DataType findValueByNumber(int number) {
                return DataType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.xiaotiangege.serialize.protobuf.Human.People.getDescriptor().getEnumTypes().get(0);
      }

      private static final DataType[] VALUES = values();

      public static DataType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private DataType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:message.People.DataType)
    }

    private int dataMsgCase_ = 0;
    private java.lang.Object dataMsg_;
    public enum DataMsgCase
        implements com.google.protobuf.Internal.EnumLite {
      STU(2),
      TEACHER(3),
      DATAMSG_NOT_SET(0);
      private final int value;
      private DataMsgCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DataMsgCase valueOf(int value) {
        return forNumber(value);
      }

      public static DataMsgCase forNumber(int value) {
        switch (value) {
          case 2: return STU;
          case 3: return TEACHER;
          case 0: return DATAMSG_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public DataMsgCase
    getDataMsgCase() {
      return DataMsgCase.forNumber(
          dataMsgCase_);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>.message.People.DataType type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.message.People.DataType type = 1;</code>
     */
    public com.xiaotiangege.serialize.protobuf.Human.People.DataType getType() {
      @SuppressWarnings("deprecation")
      com.xiaotiangege.serialize.protobuf.Human.People.DataType result = com.xiaotiangege.serialize.protobuf.Human.People.DataType.valueOf(type_);
      return result == null ? com.xiaotiangege.serialize.protobuf.Human.People.DataType.UNRECOGNIZED : result;
    }

    public static final int STU_FIELD_NUMBER = 2;
    /**
     * <code>.message.Student stu = 2;</code>
     */
    public boolean hasStu() {
      return dataMsgCase_ == 2;
    }
    /**
     * <code>.message.Student stu = 2;</code>
     */
    public com.xiaotiangege.serialize.protobuf.Human.Student getStu() {
      if (dataMsgCase_ == 2) {
         return (com.xiaotiangege.serialize.protobuf.Human.Student) dataMsg_;
      }
      return com.xiaotiangege.serialize.protobuf.Human.Student.getDefaultInstance();
    }
    /**
     * <code>.message.Student stu = 2;</code>
     */
    public com.xiaotiangege.serialize.protobuf.Human.StudentOrBuilder getStuOrBuilder() {
      if (dataMsgCase_ == 2) {
         return (com.xiaotiangege.serialize.protobuf.Human.Student) dataMsg_;
      }
      return com.xiaotiangege.serialize.protobuf.Human.Student.getDefaultInstance();
    }

    public static final int TEACHER_FIELD_NUMBER = 3;
    /**
     * <code>.message.Teacher teacher = 3;</code>
     */
    public boolean hasTeacher() {
      return dataMsgCase_ == 3;
    }
    /**
     * <code>.message.Teacher teacher = 3;</code>
     */
    public com.xiaotiangege.serialize.protobuf.Human.Teacher getTeacher() {
      if (dataMsgCase_ == 3) {
         return (com.xiaotiangege.serialize.protobuf.Human.Teacher) dataMsg_;
      }
      return com.xiaotiangege.serialize.protobuf.Human.Teacher.getDefaultInstance();
    }
    /**
     * <code>.message.Teacher teacher = 3;</code>
     */
    public com.xiaotiangege.serialize.protobuf.Human.TeacherOrBuilder getTeacherOrBuilder() {
      if (dataMsgCase_ == 3) {
         return (com.xiaotiangege.serialize.protobuf.Human.Teacher) dataMsg_;
      }
      return com.xiaotiangege.serialize.protobuf.Human.Teacher.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != com.xiaotiangege.serialize.protobuf.Human.People.DataType.TEACHER.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (dataMsgCase_ == 2) {
        output.writeMessage(2, (com.xiaotiangege.serialize.protobuf.Human.Student) dataMsg_);
      }
      if (dataMsgCase_ == 3) {
        output.writeMessage(3, (com.xiaotiangege.serialize.protobuf.Human.Teacher) dataMsg_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != com.xiaotiangege.serialize.protobuf.Human.People.DataType.TEACHER.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (dataMsgCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (com.xiaotiangege.serialize.protobuf.Human.Student) dataMsg_);
      }
      if (dataMsgCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (com.xiaotiangege.serialize.protobuf.Human.Teacher) dataMsg_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.xiaotiangege.serialize.protobuf.Human.People)) {
        return super.equals(obj);
      }
      com.xiaotiangege.serialize.protobuf.Human.People other = (com.xiaotiangege.serialize.protobuf.Human.People) obj;

      boolean result = true;
      result = result && type_ == other.type_;
      result = result && getDataMsgCase().equals(
          other.getDataMsgCase());
      if (!result) return false;
      switch (dataMsgCase_) {
        case 2:
          result = result && getStu()
              .equals(other.getStu());
          break;
        case 3:
          result = result && getTeacher()
              .equals(other.getTeacher());
          break;
        case 0:
        default:
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      switch (dataMsgCase_) {
        case 2:
          hash = (37 * hash) + STU_FIELD_NUMBER;
          hash = (53 * hash) + getStu().hashCode();
          break;
        case 3:
          hash = (37 * hash) + TEACHER_FIELD_NUMBER;
          hash = (53 * hash) + getTeacher().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.xiaotiangege.serialize.protobuf.Human.People parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xiaotiangege.serialize.protobuf.Human.People parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xiaotiangege.serialize.protobuf.Human.People parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xiaotiangege.serialize.protobuf.Human.People parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xiaotiangege.serialize.protobuf.Human.People parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xiaotiangege.serialize.protobuf.Human.People parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xiaotiangege.serialize.protobuf.Human.People parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xiaotiangege.serialize.protobuf.Human.People parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xiaotiangege.serialize.protobuf.Human.People parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.xiaotiangege.serialize.protobuf.Human.People parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xiaotiangege.serialize.protobuf.Human.People parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xiaotiangege.serialize.protobuf.Human.People parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.xiaotiangege.serialize.protobuf.Human.People prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code message.People}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:message.People)
        com.xiaotiangege.serialize.protobuf.Human.PeopleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xiaotiangege.serialize.protobuf.Human.internal_static_message_People_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xiaotiangege.serialize.protobuf.Human.internal_static_message_People_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xiaotiangege.serialize.protobuf.Human.People.class, com.xiaotiangege.serialize.protobuf.Human.People.Builder.class);
      }

      // Construct using com.xiaotiangege.serialize.protobuf.Human.People.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = 0;

        dataMsgCase_ = 0;
        dataMsg_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xiaotiangege.serialize.protobuf.Human.internal_static_message_People_descriptor;
      }

      @java.lang.Override
      public com.xiaotiangege.serialize.protobuf.Human.People getDefaultInstanceForType() {
        return com.xiaotiangege.serialize.protobuf.Human.People.getDefaultInstance();
      }

      @java.lang.Override
      public com.xiaotiangege.serialize.protobuf.Human.People build() {
        com.xiaotiangege.serialize.protobuf.Human.People result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.xiaotiangege.serialize.protobuf.Human.People buildPartial() {
        com.xiaotiangege.serialize.protobuf.Human.People result = new com.xiaotiangege.serialize.protobuf.Human.People(this);
        result.type_ = type_;
        if (dataMsgCase_ == 2) {
          if (stuBuilder_ == null) {
            result.dataMsg_ = dataMsg_;
          } else {
            result.dataMsg_ = stuBuilder_.build();
          }
        }
        if (dataMsgCase_ == 3) {
          if (teacherBuilder_ == null) {
            result.dataMsg_ = dataMsg_;
          } else {
            result.dataMsg_ = teacherBuilder_.build();
          }
        }
        result.dataMsgCase_ = dataMsgCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xiaotiangege.serialize.protobuf.Human.People) {
          return mergeFrom((com.xiaotiangege.serialize.protobuf.Human.People)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xiaotiangege.serialize.protobuf.Human.People other) {
        if (other == com.xiaotiangege.serialize.protobuf.Human.People.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        switch (other.getDataMsgCase()) {
          case STU: {
            mergeStu(other.getStu());
            break;
          }
          case TEACHER: {
            mergeTeacher(other.getTeacher());
            break;
          }
          case DATAMSG_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.xiaotiangege.serialize.protobuf.Human.People parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.xiaotiangege.serialize.protobuf.Human.People) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int dataMsgCase_ = 0;
      private java.lang.Object dataMsg_;
      public DataMsgCase
          getDataMsgCase() {
        return DataMsgCase.forNumber(
            dataMsgCase_);
      }

      public Builder clearDataMsg() {
        dataMsgCase_ = 0;
        dataMsg_ = null;
        onChanged();
        return this;
      }


      private int type_ = 0;
      /**
       * <code>.message.People.DataType type = 1;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.message.People.DataType type = 1;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.message.People.DataType type = 1;</code>
       */
      public com.xiaotiangege.serialize.protobuf.Human.People.DataType getType() {
        @SuppressWarnings("deprecation")
        com.xiaotiangege.serialize.protobuf.Human.People.DataType result = com.xiaotiangege.serialize.protobuf.Human.People.DataType.valueOf(type_);
        return result == null ? com.xiaotiangege.serialize.protobuf.Human.People.DataType.UNRECOGNIZED : result;
      }
      /**
       * <code>.message.People.DataType type = 1;</code>
       */
      public Builder setType(com.xiaotiangege.serialize.protobuf.Human.People.DataType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.message.People.DataType type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.xiaotiangege.serialize.protobuf.Human.Student, com.xiaotiangege.serialize.protobuf.Human.Student.Builder, com.xiaotiangege.serialize.protobuf.Human.StudentOrBuilder> stuBuilder_;
      /**
       * <code>.message.Student stu = 2;</code>
       */
      public boolean hasStu() {
        return dataMsgCase_ == 2;
      }
      /**
       * <code>.message.Student stu = 2;</code>
       */
      public com.xiaotiangege.serialize.protobuf.Human.Student getStu() {
        if (stuBuilder_ == null) {
          if (dataMsgCase_ == 2) {
            return (com.xiaotiangege.serialize.protobuf.Human.Student) dataMsg_;
          }
          return com.xiaotiangege.serialize.protobuf.Human.Student.getDefaultInstance();
        } else {
          if (dataMsgCase_ == 2) {
            return stuBuilder_.getMessage();
          }
          return com.xiaotiangege.serialize.protobuf.Human.Student.getDefaultInstance();
        }
      }
      /**
       * <code>.message.Student stu = 2;</code>
       */
      public Builder setStu(com.xiaotiangege.serialize.protobuf.Human.Student value) {
        if (stuBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dataMsg_ = value;
          onChanged();
        } else {
          stuBuilder_.setMessage(value);
        }
        dataMsgCase_ = 2;
        return this;
      }
      /**
       * <code>.message.Student stu = 2;</code>
       */
      public Builder setStu(
          com.xiaotiangege.serialize.protobuf.Human.Student.Builder builderForValue) {
        if (stuBuilder_ == null) {
          dataMsg_ = builderForValue.build();
          onChanged();
        } else {
          stuBuilder_.setMessage(builderForValue.build());
        }
        dataMsgCase_ = 2;
        return this;
      }
      /**
       * <code>.message.Student stu = 2;</code>
       */
      public Builder mergeStu(com.xiaotiangege.serialize.protobuf.Human.Student value) {
        if (stuBuilder_ == null) {
          if (dataMsgCase_ == 2 &&
              dataMsg_ != com.xiaotiangege.serialize.protobuf.Human.Student.getDefaultInstance()) {
            dataMsg_ = com.xiaotiangege.serialize.protobuf.Human.Student.newBuilder((com.xiaotiangege.serialize.protobuf.Human.Student) dataMsg_)
                .mergeFrom(value).buildPartial();
          } else {
            dataMsg_ = value;
          }
          onChanged();
        } else {
          if (dataMsgCase_ == 2) {
            stuBuilder_.mergeFrom(value);
          }
          stuBuilder_.setMessage(value);
        }
        dataMsgCase_ = 2;
        return this;
      }
      /**
       * <code>.message.Student stu = 2;</code>
       */
      public Builder clearStu() {
        if (stuBuilder_ == null) {
          if (dataMsgCase_ == 2) {
            dataMsgCase_ = 0;
            dataMsg_ = null;
            onChanged();
          }
        } else {
          if (dataMsgCase_ == 2) {
            dataMsgCase_ = 0;
            dataMsg_ = null;
          }
          stuBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.message.Student stu = 2;</code>
       */
      public com.xiaotiangege.serialize.protobuf.Human.Student.Builder getStuBuilder() {
        return getStuFieldBuilder().getBuilder();
      }
      /**
       * <code>.message.Student stu = 2;</code>
       */
      public com.xiaotiangege.serialize.protobuf.Human.StudentOrBuilder getStuOrBuilder() {
        if ((dataMsgCase_ == 2) && (stuBuilder_ != null)) {
          return stuBuilder_.getMessageOrBuilder();
        } else {
          if (dataMsgCase_ == 2) {
            return (com.xiaotiangege.serialize.protobuf.Human.Student) dataMsg_;
          }
          return com.xiaotiangege.serialize.protobuf.Human.Student.getDefaultInstance();
        }
      }
      /**
       * <code>.message.Student stu = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.xiaotiangege.serialize.protobuf.Human.Student, com.xiaotiangege.serialize.protobuf.Human.Student.Builder, com.xiaotiangege.serialize.protobuf.Human.StudentOrBuilder> 
          getStuFieldBuilder() {
        if (stuBuilder_ == null) {
          if (!(dataMsgCase_ == 2)) {
            dataMsg_ = com.xiaotiangege.serialize.protobuf.Human.Student.getDefaultInstance();
          }
          stuBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.xiaotiangege.serialize.protobuf.Human.Student, com.xiaotiangege.serialize.protobuf.Human.Student.Builder, com.xiaotiangege.serialize.protobuf.Human.StudentOrBuilder>(
                  (com.xiaotiangege.serialize.protobuf.Human.Student) dataMsg_,
                  getParentForChildren(),
                  isClean());
          dataMsg_ = null;
        }
        dataMsgCase_ = 2;
        onChanged();;
        return stuBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.xiaotiangege.serialize.protobuf.Human.Teacher, com.xiaotiangege.serialize.protobuf.Human.Teacher.Builder, com.xiaotiangege.serialize.protobuf.Human.TeacherOrBuilder> teacherBuilder_;
      /**
       * <code>.message.Teacher teacher = 3;</code>
       */
      public boolean hasTeacher() {
        return dataMsgCase_ == 3;
      }
      /**
       * <code>.message.Teacher teacher = 3;</code>
       */
      public com.xiaotiangege.serialize.protobuf.Human.Teacher getTeacher() {
        if (teacherBuilder_ == null) {
          if (dataMsgCase_ == 3) {
            return (com.xiaotiangege.serialize.protobuf.Human.Teacher) dataMsg_;
          }
          return com.xiaotiangege.serialize.protobuf.Human.Teacher.getDefaultInstance();
        } else {
          if (dataMsgCase_ == 3) {
            return teacherBuilder_.getMessage();
          }
          return com.xiaotiangege.serialize.protobuf.Human.Teacher.getDefaultInstance();
        }
      }
      /**
       * <code>.message.Teacher teacher = 3;</code>
       */
      public Builder setTeacher(com.xiaotiangege.serialize.protobuf.Human.Teacher value) {
        if (teacherBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dataMsg_ = value;
          onChanged();
        } else {
          teacherBuilder_.setMessage(value);
        }
        dataMsgCase_ = 3;
        return this;
      }
      /**
       * <code>.message.Teacher teacher = 3;</code>
       */
      public Builder setTeacher(
          com.xiaotiangege.serialize.protobuf.Human.Teacher.Builder builderForValue) {
        if (teacherBuilder_ == null) {
          dataMsg_ = builderForValue.build();
          onChanged();
        } else {
          teacherBuilder_.setMessage(builderForValue.build());
        }
        dataMsgCase_ = 3;
        return this;
      }
      /**
       * <code>.message.Teacher teacher = 3;</code>
       */
      public Builder mergeTeacher(com.xiaotiangege.serialize.protobuf.Human.Teacher value) {
        if (teacherBuilder_ == null) {
          if (dataMsgCase_ == 3 &&
              dataMsg_ != com.xiaotiangege.serialize.protobuf.Human.Teacher.getDefaultInstance()) {
            dataMsg_ = com.xiaotiangege.serialize.protobuf.Human.Teacher.newBuilder((com.xiaotiangege.serialize.protobuf.Human.Teacher) dataMsg_)
                .mergeFrom(value).buildPartial();
          } else {
            dataMsg_ = value;
          }
          onChanged();
        } else {
          if (dataMsgCase_ == 3) {
            teacherBuilder_.mergeFrom(value);
          }
          teacherBuilder_.setMessage(value);
        }
        dataMsgCase_ = 3;
        return this;
      }
      /**
       * <code>.message.Teacher teacher = 3;</code>
       */
      public Builder clearTeacher() {
        if (teacherBuilder_ == null) {
          if (dataMsgCase_ == 3) {
            dataMsgCase_ = 0;
            dataMsg_ = null;
            onChanged();
          }
        } else {
          if (dataMsgCase_ == 3) {
            dataMsgCase_ = 0;
            dataMsg_ = null;
          }
          teacherBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.message.Teacher teacher = 3;</code>
       */
      public com.xiaotiangege.serialize.protobuf.Human.Teacher.Builder getTeacherBuilder() {
        return getTeacherFieldBuilder().getBuilder();
      }
      /**
       * <code>.message.Teacher teacher = 3;</code>
       */
      public com.xiaotiangege.serialize.protobuf.Human.TeacherOrBuilder getTeacherOrBuilder() {
        if ((dataMsgCase_ == 3) && (teacherBuilder_ != null)) {
          return teacherBuilder_.getMessageOrBuilder();
        } else {
          if (dataMsgCase_ == 3) {
            return (com.xiaotiangege.serialize.protobuf.Human.Teacher) dataMsg_;
          }
          return com.xiaotiangege.serialize.protobuf.Human.Teacher.getDefaultInstance();
        }
      }
      /**
       * <code>.message.Teacher teacher = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.xiaotiangege.serialize.protobuf.Human.Teacher, com.xiaotiangege.serialize.protobuf.Human.Teacher.Builder, com.xiaotiangege.serialize.protobuf.Human.TeacherOrBuilder> 
          getTeacherFieldBuilder() {
        if (teacherBuilder_ == null) {
          if (!(dataMsgCase_ == 3)) {
            dataMsg_ = com.xiaotiangege.serialize.protobuf.Human.Teacher.getDefaultInstance();
          }
          teacherBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.xiaotiangege.serialize.protobuf.Human.Teacher, com.xiaotiangege.serialize.protobuf.Human.Teacher.Builder, com.xiaotiangege.serialize.protobuf.Human.TeacherOrBuilder>(
                  (com.xiaotiangege.serialize.protobuf.Human.Teacher) dataMsg_,
                  getParentForChildren(),
                  isClean());
          dataMsg_ = null;
        }
        dataMsgCase_ = 3;
        onChanged();;
        return teacherBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:message.People)
    }

    // @@protoc_insertion_point(class_scope:message.People)
    private static final com.xiaotiangege.serialize.protobuf.Human.People DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.xiaotiangege.serialize.protobuf.Human.People();
    }

    public static com.xiaotiangege.serialize.protobuf.Human.People getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<People>
        PARSER = new com.google.protobuf.AbstractParser<People>() {
      @java.lang.Override
      public People parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new People(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<People> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<People> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.xiaotiangege.serialize.protobuf.Human.People getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_Teacher_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_Teacher_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_Student_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_Student_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_People_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_People_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021proto/human.proto\022\007message\"#\n\007Teacher\022" +
      "\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\"#\n\007Student\022\n\n\002" +
      "id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\"\247\001\n\006People\022&\n\004typ" +
      "e\030\001 \001(\0162\030.message.People.DataType\022\037\n\003stu" +
      "\030\002 \001(\0132\020.message.StudentH\000\022#\n\007teacher\030\003 " +
      "\001(\0132\020.message.TeacherH\000\"$\n\010DataType\022\013\n\007T" +
      "EACHER\020\000\022\013\n\007STUDENT\020\001B\t\n\007dataMsgB,\n#com." +
      "xiaotiangege.serialize.protobufB\005Humanb\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_message_Teacher_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_message_Teacher_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_Teacher_descriptor,
        new java.lang.String[] { "Id", "Name", });
    internal_static_message_Student_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_message_Student_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_Student_descriptor,
        new java.lang.String[] { "Id", "Name", });
    internal_static_message_People_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_message_People_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_People_descriptor,
        new java.lang.String[] { "Type", "Stu", "Teacher", "DataMsg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
